package cubesrv;

public enum RotateDir {
    ORANGECW, ORANGE180, ORANGECCW, REDCW, RED180, REDCCW,
    YELLOWCW, YELLOW180, YELLOWCCW, WHITECW, WHITE180, WHITECCW,
    GREENCW, GREEN180, GREENCCW, BLUECW, BLUE180, BLUECCW,
    RCOUNT
}
